### ISSUE TITLE
how to set points

### ISSUE THREAD

**Issue by U-r-Unknown** [jaseemkm/loco-hack#1]
i have installed all requirements, tesseract is installed and is in path but getting error when i run program on a screenshot question. i have mouse pointer to get co-ordinates but how to make changes to this in program:

 **frame = i.crop(((0,400,width,650)))**

File "D:\Python36\loco-hack - Copy\play.py", line 105, in <module>
    split_screen_to_question_and_options()
  File "D:\Python36\loco-hack - Copy\play.py", line 81, in split_screen_to_question_and_options
    i = Image.open('screen.png')
  File "D:\Python36\lib\site-packages\PIL\Image.py", line 2590, in open
    % (filename if filename else fp))
OSError: cannot identify image file 'screen.png'

**Comment by jaseemkm** [comment]
Hi @U-r-Unknown 

Can you confirm you have adb connected your device?

The screen.png file is supposed to be the screenshot from the device at the instant you run the script. So most probably, you might have had something wrong with the device connection.

**Comment by U-r-Unknown** [comment]
I worked on screenshot. Not connected to adb

**Comment by U-r-Unknown** [comment]
I placed screenshot on left side on my desktop. Side of that I placed cmd screen to run program

**Comment by U-r-Unknown** [comment]
i wrked it by placing screenshot on right side of my desktop, beside that i placed cmd to run program. i thought it works on tesseract method. should i connect my mobile to pc?

**Comment by U-r-Unknown** [comment]
and raw_input is not defined in program. line 103

**Comment by jaseemkm** [comment]
for raw_input error use "python3 play.py"

**Comment by jaseemkm** [comment]
KeyError: 'items'
check wether you have entered correct api key

**Comment by Farhanshaikh6458** [comment]
Can I get your contact number so I can call u

**Comment by Farhanshaikh6458** [comment]
You can come via TeamViewer and try to short that out for me

**Comment by Farhanshaikh6458** [comment]
@jaseemkm i have checked everything still i have same error can you please help me out to short this issue only

**Comment by Sandhya-Bairi** [comment]
@jaseemkm what sites to search should i add in custom search engine? coz when i normally tried searching using it, it doesn't give many useful results.

**Comment by Sandhya-Bairi** [comment]
@jaseemkm Never mind. I changed it to entire domain and it is working. Great work.

**Comment by Farhanshaikh6458** [comment]
@Sandhya-Bairi can u help me please

**Comment by U-r-Unknown** [comment]
Farhan should we screen cast our phone on PC?

**Comment by Farhanshaikh6458** [comment]
yes @U-r-Unknown

**Comment by U-r-Unknown** [comment]
Which software r u using? Vysor?

**Comment by Farhanshaikh6458** [comment]
nope i am playing in bluestacks

**Comment by U-r-Unknown** [comment]
R u able in getting it to work?

**Comment by Farhanshaikh6458** [comment]
yes or you can try NOX player

**Comment by rajvaya** [comment]
what is the benfit of playing in emulator

**Comment by U-r-Unknown** [comment]
Many are having screen.png error. How to sort it out @jaseem bro

**Comment by mohakmalviya** [comment]
I am also getting the same error..
raw_input is not defined in program. line 103

Traceback (most recent call last):
File "C:\Python36\loco-hack\play.py", line 103, in 
a = raw_input("Wait for the next question and press Enter key instantly when it's displayed\n")
NameError: name 'raw_input' is not defined
Command - "python3 play.py" is not working....
Please help....

**Comment by urstrulyanthony** [comment]
@mohakmalviya   change **raw_input** to **input**

**Comment by arpanjayeshkumarshukla** [comment]
Use Screen Casting (via Wi-Fi or USB) and take screenshot of the desktop.

**Comment by mohakmalviya** [comment]
thanks but not resolvd....

**Comment by mohakmalviya** [comment]
Now I got another error....
OSError: cannot identify image file 'screen.png'
What can I do

**Comment by mohakmalviya** [comment]
Yes...I casted the screen of my phone to pc then also it shows error

**Comment by arpanjayeshkumarshukla** [comment]
How are you taking the screenshot? Can you post the particular snippet

**Comment by mohakmalviya** [comment]
Can u contact me at WhatsApp?

**Comment by urstrulyanthony** [comment]
@arpanjayeshkumarshukla plzz tell us the step to step process if you don't mind

**Comment by urstrulyanthony** [comment]
@arpanjayeshkumarshukla plzz tell us the step to step process if you don't mind

**Comment by mohakmalviya** [comment]
Yes....

**Comment by mohakmalviya** [comment]
I downloaded the play.py file from the website and everything shown on it

**Comment by mohakmalviya** [comment]
And I modified as u tell me to do
Then also it shows OSError

**Comment by arpanjayeshkumarshukla** [comment]
I don't know about ADB.

**Comment by mohakmalviya** [comment]
Then what i can do?

**Comment by srikantbhoi** [comment]
@arpanjayeshkumarshukla 
Can I have your email Id plzz.  I need help over some issues

**Comment by mohakmalviya** [comment]
It's only my email

**Comment by pkmuz1** [comment]
![2018-04-16_163836](https://user-images.githubusercontent.com/31066286/38805884-1b3fcb50-4195-11e8-9b7b-b9ef96c12bd2.jpg)
pls help , i'm getting api problem

**Comment by mohakmalviya** [comment]
Same here I am also getting same

**Comment by U-r-Unknown** [comment]
Its not error. U should enable billing for cse id

**Comment by mohakmalviya** [comment]
How to fix it

**Comment by Farhanshaikh6458** [comment]
https://www.youtube.com/watch?v=0oDEV-iojKE&feature=youtu.be here is the tutorial

**Comment by arpanjayeshkumarshukla** [comment]
You can set points using an application like "Cursor Position".

**Comment by rahulnaik093** [comment]
Leave this script it's a waste of time and nothing else. I can provide the best bot to hack all trivia games. Contact me a rahulnaik468@gmail.com

**Comment by Farhanshaikh6458** [comment]
Check here full tutorial video https://www.youtube.com/watch?v=Bj6rHK31cvk&feature=youtu.be

**Comment by srikantbhoi** [comment]
Ridiculous.

#šríkãnť
