### ISSUE TITLE
Billling!

### ISSUE THREAD

**Issue by akanshSirohi** [jaseemkm/loco-hack#22]
This API method requires billing to be enabled. Please enable billing on project!!!

**Comment by U-r-Unknown** [comment]
Yes u should enable billing by giving debit or credit card details

**Comment by akanshSirohi** [comment]
Thanks! But i made my own free method!

**Comment by U-r-Unknown** [comment]
How?

**Comment by U-r-Unknown** [comment]
Even that is free but it needs details. If u have found new way, u could share here. So that many will find it helpful

**Comment by akanshSirohi** [comment]
You use google vision to as an ocr! And google vision want billing! So i
remove google vision from that and make my own ocr...
Not better as google but worls fine!

**Comment by akanshSirohi** [comment]
Can u tell me how u obtain the google custom search apis

**Comment by akanshSirohi** [comment]
Because it shows error while putting options in them, so i removed option
part temporarily just search for question on google!

**Comment by Farhanshaikh6458** [comment]
Check here full tutorial video https://www.youtube.com/watch?v=Bj6rHK31cvk&feature=youtu.be

**Comment by akanshSirohi** [comment]
Which OCR do u use in your new python script!

**Comment by akanshSirohi** [comment]
Can you tell me zip password?

**Comment by akanshSirohi** [comment]
I think u use voice search!

**Comment by akanshSirohi** [comment]
I tried your method 1 and method 2 in previous scrict, i successfully get
both the keys and setup my own ocr but the methods not showing appropriate
answers!

**Comment by akanshSirohi** [comment]
What is inside the zip file you are talking about on ur blog?
