### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by nick-nagaraj** [jaseemkm/loco-hack#3]
Can you please create a step by step tutorial?
I've input my cse_id and api_id. But, I'm getting multiple errors. 
Please upload a tutorial

**Comment by arpanjayeshkumarshukla** [comment]
Please post your errors, so others can help too

**Comment by urstrulyanthony** [comment]
is api_key free

**Comment by arpanjayeshkumarshukla** [comment]
Yes, it is free. However, number of searches per day are limited.

**Comment by Farhanshaikh6458** [comment]
Check here full tutorial video https://www.youtube.com/watch?v=Bj6rHK31cvk&feature=youtu.be

**Comment by jaseemkm** [comment]
Setup tutorial https://youtu.be/7dHTeOUEDps
