### ISSUE TITLE
TUTORIAL

### ISSUE THREAD

**Issue by urstrulyanthony** [jaseemkm/loco-hack#6]
i have completely debugged the code and its working
can someone tell me the further procedure please asap

**Comment by urstrulyanthony** [comment]
i have done the implementation completely
now i need to know what is the further procedure

**Comment by urstrulyanthony** [comment]
i mean what is the exact procedure of capturing the image

**Comment by urstrulyanthony** [comment]
@arpanjayeshkumarshukla can u plz reply

**Comment by arpanjayeshkumarshukla** [comment]
You have to use a library for that -> pyscreenshot.
