### ISSUE TITLE
Name error

### ISSUE THREAD

**Issue by shreyas24cool** [jaseemkm/loco-hack#8]
Name error raw_input is not defined

**Comment by arpanjayeshkumarshukla** [comment]
raw_input is Python 2 code. use input for Python 3 code.

**Comment by U-r-Unknown** [comment]
Change raw_input to input in code

**Comment by U-r-Unknown** [comment]
Shreyas wats happening abt loco code?

**Comment by shreyas24cool** [comment]
Its under development

**Comment by arpanjayeshkumarshukla** [comment]
@shreyas24cool Are you able to obtain questions through the web socket?

**Comment by shreyas24cool** [comment]
Ya the script needs development to connect to socket with the given sid which changes everytime we click the socket

**Comment by arpanjayeshkumarshukla** [comment]
Can't we obtain the sid at 9:55 PM when the game starts?

**Comment by shreyas24cool** [comment]
Yes but not only sid the socket needs your authorisation credentials

**Comment by arpanjayeshkumarshukla** [comment]
That will always remain the same. User can configure the details in a text file.

**Comment by shreyas24cool** [comment]
Yes

**Comment by arpanjayeshkumarshukla** [comment]
What is currently under development then

**Comment by shreyas24cool** [comment]
Its work mechanism is not like HQ Trivia
The script for connecting to socket and obtain questions in under development.
